title: Mohd Aliyan # your name (or website title) here
logo: "/profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Senior Backend Developer
  <br><br>
  <a href="mailto:mohd.aliyan.mca@gmail.com">mohd.aliyan.mca@gmail.com </a>
  <br>
  <a href="https://www.linkedin.com/in/mohdaliyan/">LinkedIn Profile</a>
  <br>
  <a href="https://github.com/MohdAliyan27/">Github</a> 
   <br>
    <br>
     <br>
      <br>
theme: jekyll-theme-minimal
